version: '3'
services:
  api:
    build: ./api
    container_name: backend-flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True                   
    restart: on-failure
    volumes:
      - ./api:/api
    ports:
      - "5000:5000"
    command: python main.py
